### ISSUE TITLE
Compilation error on Ubuntu 22.04

### ISSUE THREAD

**Issue by pkeir** [jwakely/pkg-gcc-latest#6]
First of all, thank you for making this excellent resource available.

On Ubuntu 22.04 I find that compiling "hello world" produces errors starting with a (perhaps pre-existing) typedef of `_Float128` in `/usr/include/x86_64-linux-gnu/bits/floatn.h`. I am using `gcc-latest_13.0.0-20221009gite95e91eccd02.deb`. With the earlier `gcc-latest_13.0.0-20220626gitff35dbc02092.deb` there is no problem. Details are below:

```
$ cat hello.cpp
#include <iostream>

int main(int argc, char *argv[])
{
  std::cout << "Hello\n";
  return 0;
}
$ /opt/gcc-latest/bin/g++ hello.cpp 
In file included from /usr/include/wchar.h:30,
                 from /opt/gcc-latest/include/c++/13.0.0/cwchar:44,
                 from /opt/gcc-latest/include/c++/13.0.0/bits/postypes.h:40,
                 from /opt/gcc-latest/include/c++/13.0.0/iosfwd:42,
                 from /opt/gcc-latest/include/c++/13.0.0/ios:40,
                 from /opt/gcc-latest/include/c++/13.0.0/ostream:40,
                 from /opt/gcc-latest/include/c++/13.0.0/iostream:41,
                 from hello.cpp:1:
/usr/include/x86_64-linux-gnu/bits/floatn.h:86:9: error: multiple types in one declaration
   86 | typedef __float128 _Float128;
      |         ^~~~~~~~~~
/usr/include/x86_64-linux-gnu/bits/floatn.h:86:20: error: declaration does not declare anything [-fpermissive]
   86 | typedef __float128 _Float128;
      |                    ^~~~~~~~~
In file included from /usr/include/x86_64-linux-gnu/bits/floatn.h:119:
/usr/include/x86_64-linux-gnu/bits/floatn-common.h:214:9: error: multiple types in one declaration
  214 | typedef float _Float32;
      |         ^~~~~
/usr/include/x86_64-linux-gnu/bits/floatn-common.h:214:15: error: declaration does not declare anything [-fpermissive]
  214 | typedef float _Float32;
      |               ^~~~~~~~
/usr/include/x86_64-linux-gnu/bits/floatn-common.h:251:9: error: multiple types in one declaration
  251 | typedef double _Float64;
      |         ^~~~~~
/usr/include/x86_64-linux-gnu/bits/floatn-common.h:251:16: error: declaration does not declare anything [-fpermissive]
  251 | typedef double _Float64;
      |                ^~~~~~~~
/usr/include/x86_64-linux-gnu/bits/floatn-common.h:268:9: error: multiple types in one declaration
  268 | typedef double _Float32x;
      |         ^~~~~~
/usr/include/x86_64-linux-gnu/bits/floatn-common.h:268:16: error: declaration does not declare anything [-fpermissive]
  268 | typedef double _Float32x;
      |                ^~~~~~~~~
/usr/include/x86_64-linux-gnu/bits/floatn-common.h:285:14: error: multiple types in one declaration
  285 | typedef long double _Float64x;
      |              ^~~~~~
/usr/include/x86_64-linux-gnu/bits/floatn-common.h:285:21: error: declaration does not declare anything [-fpermissive]
  285 | typedef long double _Float64x;
      |                     ^~~~~~~~~
```

**Comment by jwakely** [comment]
I'll make that change, so that next Monday's snapshot will be built on 18.04 and should work on 22.04.

In the meantime, you should be able to use https://kayari.org/gcc-latest/gcc-latest_13.0.0-20220925git77bbf69d2981.deb instead. That's the last build before the built-in `_Float128` type was added to G++.

**Comment by pkeir** [comment]
Thanks for the explanation. That sounds like a sensible solution. The 0925 version is also much appreciated.

**Comment by jwakely** [comment]
I fixed it by regenerating the fixincludes after installation, so Monday's package will still work on 16.04 but also on later releases (tested with 20.04 and 22.04).
